// 系统预设默认模型（唯一权威来源）
// 供 /api/data/models 路由与 db.ts 的 seedUserDefaultModels 共用，
// 避免 "3 个旧模型" 与 "12 个新模型" 两份定义漂移。
export const DEFAULT_MODELS = [
  {
    model_id: "ark-plan-text",
    name: "火山方舟 Agent Plan（文本+图片理解）",
    provider: "字节跳动火山方舟",
    base_url: "https://ark.cn-beijing.volces.com/api/plan/v3/chat/completions",
    protocol: "OpenAI 兼容协议",
    type: "text",
    model_slug: "ark-code-latest",
    status: "active",
    api_key: "",
  },
  {
    model_id: "ark-text",
    name: "火山方舟 Coding Plan（订阅已过期）",
    provider: "字节跳动火山方舟",
    base_url: "https://ark.cn-beijing.volces.com/api/coding/v3/chat/completions",
    protocol: "OpenAI 兼容协议",
    type: "text",
    model_slug: "",
    status: "disabled",
    api_key: "",
  },
  {
    model_id: "minimax-text",
    name: "MiniMax Claude 2.7",
    provider: "MiniMax (海螺AI)",
    base_url: "https://api.minimaxi.com/anthropic/v1/messages",
    protocol: "Anthropic Messages API",
    type: "text",
    model_slug: "",
    status: "active",
    api_key: "",
  },
  {
    model_id: "ark-image",
    name: "火山方舟 Seedream 4.0",
    provider: "字节跳动火山方舟",
    base_url: "https://ark.cn-beijing.volces.com/api/v3/images/generations",
    protocol: "OpenAI 兼容协议",
    type: "image",
    model_slug: "",
    status: "active",
    api_key: "",
  },
  {
    model_id: "minimax-image",
    name: "MiniMax Image-01（额度已用尽）",
    provider: "MiniMax (海螺AI)",
    base_url: "https://api.minimaxi.com/v1/image_generation",
    protocol: "MiniMax 原生协议",
    type: "image",
    model_slug: "",
    status: "disabled",
    api_key: "",
  },
  {
    model_id: "minimax-video",
    name: "MiniMax T2V-01（套餐未开通）",
    provider: "MiniMax (海螺AI)",
    base_url: "https://api.minimaxi.com/v1/video_generation",
    protocol: "MiniMax 原生协议",
    type: "video",
    model_slug: "",
    status: "disabled",
    api_key: "",
  },
  {
    model_id: "hunyuan-video",
    name: "腾讯混元 hy-video-1.5（账号欠费）",
    provider: "腾讯混元",
    base_url: "https://tokenhub.tencentmaas.com/v1/api/video/submit",
    protocol: "腾讯混元 API",
    type: "video",
    model_slug: "",
    status: "disabled",
    api_key: "",
  },
  {
    model_id: "hunyuan-image",
    name: "腾讯混元 Image（端点已失效）",
    provider: "腾讯混元",
    base_url: "https://tokenhub.tencentmaas.com/v1/api/image/generate",
    protocol: "腾讯混元 API",
    type: "image",
    model_slug: "",
    status: "disabled",
    api_key: "",
  },
  {
    model_id: "agnes-image",
    name: "Agnes AI Image 2.1 Flash",
    provider: "Agnes AI",
    base_url: "https://apihub.agnes-ai.com/v1/images/generations",
    protocol: "OpenAI 兼容协议",
    type: "image",
    model_slug: "",
    status: "active",
    api_key: "",
  },
  {
    model_id: "agnes-video",
    name: "Agnes AI Video V2.0",
    provider: "Agnes AI",
    base_url: "https://apihub.agnes-ai.com/v1/videos",
    protocol: "OpenAI 兼容协议",
    type: "video",
    model_slug: "agnes-video-v2.0",
    status: "active",
    api_key: "",
  },
  {
    model_id: "agnes-video-25",
    name: "Agnes AI Video 2.5（需 Token Plan 付费计划）",
    provider: "Agnes AI",
    base_url: "https://apihub.agnes-ai.com/v1/videos",
    protocol: "OpenAI Videos 兼容协议",
    type: "video",
    model_slug: "agnes-video-2.5",
    status: "disabled",
    api_key: "",
  },
  {
    model_id: "seedance-mini-video",
    name: "Seedance 2 Mini（中转额度耗尽）",
    provider: "ByteDance (AggregateAPI)",
    base_url: "https://aaapi.togomol.com/api/v1/tasks",
    protocol: "AggregateAPI 异步任务",
    type: "video",
    model_slug: "",
    status: "disabled",
    api_key: "",
  },
];

// 内置模型 id：密钥一律服务端托管，不落库、不下发前端
export const BUILTIN_MODEL_IDS = new Set([
  "ark-text",
  "ark-plan-text",
  "ark-image",
  "minimax-text",
  "minimax-image",
  "minimax-video",
  "hunyuan-video",
  "hunyuan-image",
  "agnes-image",
  "agnes-video",
  "agnes-video-25",
  "seedance-mini-video",
]);
